# Generated by Django 2.2.4 on 2020-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
