# Generated by Django 2.2.4 on 2020-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_urls', '0006_remove_url_shorten_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shorten_url',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
