# Generated by Django 2.2.4 on 2020-03-18 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_urls', '0011_auto_20200318_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shorten_url',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
