# Generated by Django 2.2.4 on 2020-03-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_urls', '0013_remove_url_shorten_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shorten_url',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
    ]
