# Generated by Django 2.2.4 on 2020-03-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_urls', '0014_url_shorten_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('visitor_name', models.CharField(default='', max_length=100)),
                ('visitor_ip', models.GenericIPAddressField()),
                ('visitor_device', models.IntegerField(default=1)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='UrlShortener_urls.Url')),
            ],
            options={
                'unique_together': {('visitor_name', 'visitor_ip')},
            },
        ),
    ]
