# Generated by Django 2.2.4 on 2020-03-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_urls', '0015_urlvisit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='urlvisit',
            unique_together=set(),
        ),
    ]
