# Generated by Django 2.2.4 on 2020-03-19 06:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_urls', '0016_auto_20200318_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(editable=False)),
                ('visitor_name', models.CharField(default='', max_length=100)),
                ('visitor_ip', models.GenericIPAddressField()),
                ('visitor_device', models.IntegerField(default=1)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='UrlShortener_urls.Url')),
            ],
        ),
        migrations.DeleteModel(
            name='UrlVisit',
        ),
    ]
