# Generated by Django 2.2.4 on 2020-03-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_urls', '0018_remove_urlvisits_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlvisits',
            name='visitor_browser',
            field=models.CharField(default='', max_length=30),
        ),
    ]
