# Generated by Django 2.2.4 on 2020-03-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortener_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='name',
        ),
    ]
